#!/bin/sh
names=( 'nBunchXing' 'nMuons' 'nElectrons' 'nTaus' 'nPhotons' 'nJets' 'nFatJets' 'nGenJets' 'nGenParticle' 'nIsoPFCandidates')
maxes=( 20 40 40 40 40 50 40 50 4000 40 )

cp include/RazorEvents.h RazorEventsNewTemp.h
for ((i=0;i<${#names[@]};++i)); do
    name=${names[$i]}
    sed "s/\([0-9][0-9]*\)\(\];\s*\/\/\[${name}\]\)/${maxes[$i]}\2/" <RazorEventsNewTemp.h >RazorEventsNew.h
    cp RazorEventsNew.h RazorEventsNewTemp.h
done
rm RazorEventsNewTemp.h
mv RazorEventsNew.h include/RazorEvents.h
