#!/bin/sh

if [ "$1" == "" ] || [ "$2" == "" ]; then
    echo "RazorRun <list of input files> <analyzer name> <options>"
else
    cp ${CMSSW_BASE}/src/RazorAnalyzer/bin/Run$2 .
    ./Run$2 $1 ${@:3}
    rm Run$2
fi
