#!/bin/sh
if [[ $1 == "" ]] 
then 
    echo "Error: please specify directory where target lists are located"
    exit
fi
if [[ $1 != lists* ]]
then
    echo "Error: this script must be run from the top-level RazorAnalyzer directory"
    exit
fi
tmp=$1
tmp=${tmp#*/}
dirName=${tmp%/}
if [ ! -d "output/$dirName" ]; then
    mkdir output/$dirName
fi
normFilename="lists/filestonormalize/RazorInclusiveMC_$dirName.txt"
echo '#Format: <dataset name> <root file name>' > $normFilename
listSuffix=".txt"
for file in $( ls -Sr $1 ); do
    make clean
    make
    fullFile=lists/$dirName/$file
    ./RazorRun $fullFile razor
    outFilename=output/$dirName/RazorInclusive${file%$listSuffix}.root
    mv RazorInclusive.root $outFilename
    echo "${file%$listSuffix} $outFilename" >> $normFilename #NOTE this assumes the lists have same names as the datasets
done
make clean
make
./NormalizeNtuple $normFilename
hadd output/RazorInclusiveMCWeighted_$dirName.root output/$dirName/*weighted.root
